### ISSUE TITLE
Espresso Testing?

### ISSUE THREAD

**Issue by Polyterative** [afollestad/rxkprefs#2]
I'm trying to use this lib in an Espresso environment

I've had some trouble making the lib work. I've tried 2 approaches getting a`Context`

`MockContext()` makes everything crash 
`InstrumentationRegistry.getInstrumentation().context` doesn't crash but makes no changes to my preferences

**Comment by afollestad** [comment]
What exactly does your code look like?

You should be passing the instrumentation context into `rxkPrefs(...)`.
