### ISSUE TITLE
Context separation

### ISSUE THREAD

**Issue by Polyterative** [afollestad/rxkprefs#3]
It should be noted in the docs that cross-observing from `applicationContext` and a classic activity `context` yields different results. 
If I want to observe change I should always use the same type of context in a given moment

**Comment by afollestad** [comment]
That shouldn't be true. Activity context and Application context should be retrieving the same `SharedPreferences` pool, Android internally caches them in memory to optimize file access.

**Comment by Polyterative** [comment]
I'll investigate futher then, probably a bug of my application at this point
